lib/votes_web/router.ex
defmodule VotesWeb.Router do
  use VotesWeb, :router
  use Kaffy.Routes #, scope: "/admin", pipe_through: [:some_plug, :authenticate]

  import VotesWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {VotesWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :api_authenticated do
    plug VotesWeb.AuthAccessPipeline
  end

  pipeline :graphql do
    plug VotesWeb.Context
  end

  scope "/api" do
    pipe_through :graphql

    forward "/", Absinthe.Plug, schema: VotesWeb.Schema
  end

  scope "/", VotesWeb do
    pipe_through :browser

    live "/", PageLive, :index
    live "/light", LightLive
  end

  # Other scopes may use custom stacks.
  # scope "/api", VotesWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: VotesWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", VotesWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated, :put_session_layout]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", VotesWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
    put "/users/settings/update_avatar", UserSettingsController, :update_avatar
  end

  scope "/", VotesWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  if Mix.env == :dev do
    forward "/graphiql", Absinthe.Plug.GraphiQL, schema: VotesWeb.Schema
  end
end

lib/votes_web/controllers/user_registration_controller.ex
defmodule VotesWeb.UserRegistrationController do
  use VotesWeb, :controller

  alias Votes.Accounts
  alias Votes.Accounts.User
  alias VotesWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :confirm, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/votes_web/views/user_registration_view.ex
defmodule VotesWeb.UserRegistrationView do
  use VotesWeb, :view
end

lib/votes_web/templates/user_registration/new.html.eex
<h5 class="px-5 pb-2 text-lg leading-normal text-center">Register</h5>
<%= form_for @changeset, Routes.user_registration_path(@conn, :create), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <small>Oops, something went wrong! Please check the errors below.</small>
    </div>
  <% end %>

  <div class="mt-4 mb-4">
    <%= label f, :email, class: "form-label" %>
    <%= text_input f, :email, required: true, class: "form-input" %>
    <%= error_tag f, :email %>
  </div>

  <div class="mb-4">
    <%= label f, :password, class: "form-label" %>
    <%= password_input f, :password, required: true, class: "form-input" %>
    <%= error_tag f, :password %>
  </div>

  <div class="mt-6">
    <%= submit "Register", class: "btn btn-dark w-full" %>
  </div>
<% end %>

<div class="mt-3 text-center text-gray-600">
  <small>Already have an account?</small>
</div>

<div class="mt-3">
  <%= link "Log in", to: Routes.user_session_path(@conn, :new), class: "btn btn-link btn-sm" %>
  <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "btn btn-link btn-sm" %>
</div>